### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by tejas-hosamani** [cetorres/ai-buddy#2]
Hi, thank you for creating this.

I am trying to run on my device, but it doesn't seem to work. 

<img width="482" alt="image" src="https://github.com/user-attachments/assets/46551f75-a90e-4b4a-9692-1dcc4ec720e9">

I cloned the repo, ran three commands in order but it seems to not recognize the command.
Am I missing something?

--

Then I tried running the main go directly, and I get the following error
<img width="895" alt="image" src="https://github.com/user-attachments/assets/42954e39-e58c-4fcc-bbeb-40d42ba41730">

I did export llama's host:
<img width="496" alt="image" src="https://github.com/user-attachments/assets/86906d00-5fca-4050-a828-34e3327a0423">

What can I do to get started?

I am not a 'go' developer

**Comment by cetorres** [comment]
As you are not a developer, you can just download the latest release binary and use it directly on your system: https://github.com/cetorres/ai-buddy/releases

**Comment by tejas-hosamani** [comment]
Okay. 
Which one runs on Mac? I didn't see specific Mac release in any names. Darwin works?

---
With darwin
<img width="274" alt="image" src="https://github.com/user-attachments/assets/3d1c370e-a596-4100-afa5-be72278dcec7">

**Comment by cetorres** [comment]
Yes

**Comment by tejas-hosamani** [comment]
Same issue on this as well - 
<img width="501" alt="image" src="https://github.com/user-attachments/assets/b15a091b-202c-4710-9f0a-d1c4afceefd7">

**Comment by cetorres** [comment]
Read the README. You need to inform at least one API key, either Google Gemini or ChatGPT. Otherwise use Ollama.

**Comment by tejas-hosamani** [comment]
I am using llama, I have added host for llama, gave a model name in the command as well.

**Comment by tejas-hosamani** [comment]
Tried with web-ui too, no luck 
<img width="1731" alt="image" src="https://github.com/user-attachments/assets/7ebcac24-2fa5-44c8-a9b2-60c7bc8c1d04">

**Comment by cetorres** [comment]
Do you have Ollama running correctly in you computer?

**Comment by tejas-hosamani** [comment]
Yes, I have been using it for weeks. In fact, I just tried with fabric and its working fine

**Comment by cetorres** [comment]
On the terminal command you need to add `-o` flag after the pattern name to tell the program to use Ollama

**Comment by tejas-hosamani** [comment]
Ah crap, I missed that. Works now, thank you!
