### ISSUE TITLE
No pattern listed in the web ui

### ISSUE THREAD

**Issue by vhongtuanha** [cetorres/ai-buddy#4]
Hi 
Using the last version 1.1.4 and the previous one on windows 11
I can select the provider , the model, but the list of patterns is empty ( patterns folder is the default one)

I defined using
AI_BUDDY_PATTERNS
but its still not finding the pattern list

Maybe this can help too. When i run the web ui i have this message:
2024/08/02 16:05:13 ERROR unable to locate llm runner directory.  Set OLLAMA_RUNNERS_DIR to the location of 'ollama_runners'

![image](https://github.com/user-attachments/assets/39a144c3-5158-46a1-ab3f-0b5c82190ff4)

**Comment by cetorres** [comment]
Hi, I'm releasing v.1.1.5 soon that will bring a few changes to the configuration, including how to handle the patterns directory. Please wait for the release, download it, and try again.
Thanks.

**Comment by cetorres** [comment]
v.1.1.5 released. Please test it. Thanks.

**Comment by vhongtuanha** [comment]
Its still the same

2024/08/03 08:48:45 ERROR unable to locate llm runner directory.  Set OLLAMA_RUNNERS_DIR to the location of 'ollama_runners'
ai-buddy server running on http://127.0.0.1:8081
2024/08/03 08:48:52 http: panic serving 127.0.0.1:2632: runtime error: index out of range [1] with length 1
goroutine 20 [running]:
net/http.(*conn).serve.func1()
        /usr/local/go/src/net/http/server.go:1903 +0xbe
panic({0x87c4c0?, 0xc0000bcaf8?})
        /usr/local/go/src/runtime/panic.go:770 +0x132
github.com/cetorres/ai-buddy/pattern.GetPatternList.func1({0xc000110c80, 0x36}, {0xa46768, 0xc00035a070}, {0x0?, 0x0?})
        /github/workspace/pattern/pattern.go:48 +0x266
path/filepath.walk({0xc000110c80, 0x36}, {0xa46768, 0xc00035a070}, 0xc0001eda08)
        /usr/local/go/src/path/filepath/path.go:482 +0xae
path/filepath.walk({0xc0004a93e0, 0x28}, {0xa46768, 0xc00035a000}, 0xc0001eda08)
        /usr/local/go/src/path/filepath/path.go:502 +0x254
path/filepath.Walk({0xc0004a93e0, 0x28}, 0xc0001eda08)
        /usr/local/go/src/path/filepath/path.go:560 +0x66
github.com/cetorres/ai-buddy/pattern.GetPatternList()
        /github/workspace/pattern/pattern.go:42 +0x88
github.com/cetorres/ai-buddy/server.handleGetPatterns({0xa428c0, 0xc0004b80e0}, 0xc0001edb30?)
        /github/workspace/server/server.go:144 +0x58
net/http.HandlerFunc.ServeHTTP(0xf99760?, {0xa428c0?, 0xc0004b80e0?}, 0x39741a?)
        /usr/local/go/src/net/http/server.go:2171 +0x29
net/http.(*ServeMux).ServeHTTP(0xf92f9?, {0xa428c0, 0xc0004b80e0}, 0xc00036db00)
        /usr/local/go/src/net/http/server.go:2688 +0x1ad
net/http.serverHandler.ServeHTTP({0xc0001081e0?}, {0xa428c0?, 0xc0004b80e0?}, 0x6?)
        /usr/local/go/src/net/http/server.go:3142 +0x8e
net/http.(*conn).serve(0xc0003f6510, {0xa43a88, 0xc000389860})
        /usr/local/go/src/net/http/server.go:2044 +0x5e8
created by net/http.(*Server).Serve in goroutine 1
        /usr/local/go/src/net/http/server.go:3290 +0x4b4
2024/08/03 08:48:52 http: panic serving 127.0.0.1:2630: runtime error: index out of range [1] with length 1
goroutine 18 [running]:
net/http.(*conn).serve.func1()
        /usr/local/go/src/net/http/server.go:1903 +0xbe
panic({0x87c4c0?, 0xc0003045a0?})
        /usr/local/go/src/runtime/panic.go:770 +0x132
github.com/cetorres/ai-buddy/pattern.GetPatternList.func1({0xc00002e280, 0x36}, {0xa46768, 0xc0000d0770}, {0x0?, 0x0?})
        /github/workspace/pattern/pattern.go:48 +0x266
path/filepath.walk({0xc00002e280, 0x36}, {0xa46768, 0xc0000d0770}, 0xc000049a08)
        /usr/local/go/src/path/filepath/path.go:482 +0xae
path/filepath.walk({0xc00032e030, 0x28}, {0xa46768, 0xc0000d0000}, 0xc000049a08)
        /usr/local/go/src/path/filepath/path.go:502 +0x254
path/filepath.Walk({0xc00032e030, 0x28}, 0xc000049a08)
        /usr/local/go/src/path/filepath/path.go:560 +0x66
github.com/cetorres/ai-buddy/pattern.GetPatternList()
        /github/workspace/pattern/pattern.go:42 +0x88
github.com/cetorres/ai-buddy/server.handleGetPatterns({0xa428c0, 0xc000180a80}, 0xc000049b30?)
        /github/workspace/server/server.go:144 +0x58
net/http.HandlerFunc.ServeHTTP(0xf99760?, {0xa428c0?, 0xc000180a80?}, 0x39741a?)
        /usr/local/go/src/net/http/server.go:2171 +0x29
net/http.(*ServeMux).ServeHTTP(0xf92f9?, {0xa428c0, 0xc000180a80}, 0xc000302000)
        /usr/local/go/src/net/http/server.go:2688 +0x1ad
net/http.serverHandler.ServeHTTP({0xc000389950?}, {0xa428c0?, 0xc000180a80?}, 0x6?)
        /usr/local/go/src/net/http/server.go:3142 +0x8e
net/http.(*conn).serve(0xc0003f6360, {0xa43a88, 0xc000389860})
        /usr/local/go/src/net/http/server.go:2044 +0x5e8
created by net/http.(*Server).Serve in goroutine 1
        /usr/local/go/src/net/http/server.go:3290 +0x4b4
2024/08/03 08:48:52 http: panic serving 127.0.0.1:2631: runtime error: index out of range [1] with length 1
goroutine 34 [running]:
net/http.(*conn).serve.func1()
        /usr/local/go/src/net/http/server.go:1903 +0xbe
panic({0x87c4c0?, 0xc000030a98?})
        /usr/local/go/src/runtime/panic.go:770 +0x132
github.com/cetorres/ai-buddy/pattern.GetPatternList.func1({0xc000492180, 0x36}, {0xa46768, 0xc0001e4070}, {0x0?, 0x0?})
        /github/workspace/pattern/pattern.go:48 +0x266
path/filepath.walk({0xc000492180, 0x36}, {0xa46768, 0xc0001e4070}, 0xc000533a08)
        /usr/local/go/src/path/filepath/path.go:482 +0xae
path/filepath.walk({0xc0005eeea0, 0x28}, {0xa46768, 0xc0001e4000}, 0xc000533a08)
        /usr/local/go/src/path/filepath/path.go:502 +0x254
path/filepath.Walk({0xc0005eeea0, 0x28}, 0xc000533a08)
        /usr/local/go/src/path/filepath/path.go:560 +0x66
github.com/cetorres/ai-buddy/pattern.GetPatternList()
        /github/workspace/pattern/pattern.go:42 +0x88
github.com/cetorres/ai-buddy/server.handleGetPatterns({0xa428c0, 0xc00040e2a0}, 0x9?)
        /github/workspace/server/server.go:144 +0x58
net/http.HandlerFunc.ServeHTTP(0xf99760?, {0xa428c0?, 0xc00040e2a0?}, 0x39741a?)
        /usr/local/go/src/net/http/server.go:2171 +0x29
net/http.(*ServeMux).ServeHTTP(0xf92f9?, {0xa428c0, 0xc00040e2a0}, 0xc00048fe60)
        /usr/local/go/src/net/http/server.go:2688 +0x1ad
net/http.serverHandler.ServeHTTP({0xc0001080c0?}, {0xa428c0?, 0xc00040e2a0?}, 0x6?)
        /usr/local/go/src/net/http/server.go:3142 +0x8e
net/http.(*conn).serve(0xc00010a090, {0xa43a88, 0xc000389860})
        /usr/local/go/src/net/http/server.go:2044 +0x5e8
created by net/http.(*Server).Serve in goroutine 1
        /usr/local/go/src/net/http/server.go:3290 +0x4b4
2024/08/03 08:48:52 http: panic serving 127.0.0.1:2634: runtime error: index out of range [1] with length 1
goroutine 50 [running]:
net/http.(*conn).serve.func1()
        /usr/local/go/src/net/http/server.go:1903 +0xbe
panic({0x87c4c0?, 0xc000031068?})
        /usr/local/go/src/runtime/panic.go:770 +0x132
github.com/cetorres/ai-buddy/pattern.GetPatternList.func1({0xc000492280, 0x36}, {0xa46768, 0xc0001e4150}, {0x0?, 0x0?})
        /github/workspace/pattern/pattern.go:48 +0x266
path/filepath.walk({0xc000492280, 0x36}, {0xa46768, 0xc0001e4150}, 0xc000265a08)
        /usr/local/go/src/path/filepath/path.go:482 +0xae
path/filepath.walk({0xc0005eefc0, 0x28}, {0xa46768, 0xc0001e40e0}, 0xc000265a08)
        /usr/local/go/src/path/filepath/path.go:502 +0x254
path/filepath.Walk({0xc0005eefc0, 0x28}, 0xc000265a08)
        /usr/local/go/src/path/filepath/path.go:560 +0x66
github.com/cetorres/ai-buddy/pattern.GetPatternList()
        /github/workspace/pattern/pattern.go:42 +0x88
github.com/cetorres/ai-buddy/server.handleGetPatterns({0xa428c0, 0xc00040e380}, 0x9?)
        /github/workspace/server/server.go:144 +0x58
net/http.HandlerFunc.ServeHTTP(0xf99760?, {0xa428c0?, 0xc00040e380?}, 0x39741a?)
        /usr/local/go/src/net/http/server.go:2171 +0x29
net/http.(*ServeMux).ServeHTTP(0xf92f9?, {0xa428c0, 0xc00040e380}, 0xc0004c6000)
        /usr/local/go/src/net/http/server.go:2688 +0x1ad
net/http.serverHandler.ServeHTTP({0xc000482120?}, {0xa428c0?, 0xc00040e380?}, 0x6?)
        /usr/local/go/src/net/http/server.go:3142 +0x8e
net/http.(*conn).serve(0xc000496000, {0xa43a88, 0xc000389860})
        /usr/local/go/src/net/http/server.go:2044 +0x5e8
created by net/http.(*Server).Serve in goroutine 1
        /usr/local/go/src/net/http/server.go:3290 +0x4b4
2024/08/03 08:48:52 http: panic serving 127.0.0.1:2637: runtime error: index out of range [1] with length 1
goroutine 58 [running]:
net/http.(*conn).serve.func1()
        /usr/local/go/src/net/http/server.go:1903 +0xbe
panic({0x87c4c0?, 0xc0000bc7c8?})
        /usr/local/go/src/runtime/panic.go:770 +0x132
github.com/cetorres/ai-buddy/pattern.GetPatternList.func1({0xc000110180, 0x36}, {0xa46768, 0xc00035a070}, {0x0?, 0x0?})
        /github/workspace/pattern/pattern.go:48 +0x266
path/filepath.walk({0xc000110180, 0x36}, {0xa46768, 0xc00035a070}, 0xc000379a08)
        /usr/local/go/src/path/filepath/path.go:482 +0xae
path/filepath.walk({0xc0004a8030, 0x28}, {0xa46768, 0xc00035a000}, 0xc000379a08)
        /usr/local/go/src/path/filepath/path.go:502 +0x254
path/filepath.Walk({0xc0004a8030, 0x28}, 0xc000379a08)
        /usr/local/go/src/path/filepath/path.go:560 +0x66
github.com/cetorres/ai-buddy/pattern.GetPatternList()
        /github/workspace/pattern/pattern.go:42 +0x88
github.com/cetorres/ai-buddy/server.handleGetPatterns({0xa428c0, 0xc00040e1c0}, 0xc000379b30?)
        /github/workspace/server/server.go:144 +0x58
net/http.HandlerFunc.ServeHTTP(0xf99760?, {0xa428c0?, 0xc00040e1c0?}, 0x39741a?)
        /usr/local/go/src/net/http/server.go:2171 +0x29
net/http.(*ServeMux).ServeHTTP(0xf92f9?, {0xa428c0, 0xc00040e1c0}, 0xc0004c6120)
        /usr/local/go/src/net/http/server.go:2688 +0x1ad
net/http.serverHandler.ServeHTTP({0xc00037c090?}, {0xa428c0?, 0xc00040e1c0?}, 0x6?)
        /usr/local/go/src/net/http/server.go:3142 +0x8e
net/http.(*conn).serve(0xc000496090, {0xa43a88, 0xc000389860})
        /usr/local/go/src/net/http/server.go:2044 +0x5e8
created by net/http.(*Server).Serve in goroutine 1
        /usr/local/go/src/net/http/server.go:3290 +0x4b4

**Comment by cetorres** [comment]
I gotta get a hold of a Windows machine to test. In the meantime tell me what you did after you downloaded the release and unzipped it.

**Comment by vhongtuanha** [comment]
Sure.
1. Start the command line at the unzipped folder
2. Set in the command line: SET AI_BUDDY_SERVER_PORT=8081 (only with 1.1.4)
3. ai-buddy.exe -w --port 8081ai-buddy.exe -w --port 8081

There i can't select patterns cause the list is empty

**Comment by cetorres** [comment]
Now the program needs a setup. Just run `ai-buddy` just after you unzipped, or run `ai-buddy --setup` manually. It will start the setup process. You can just hit enter on the API keys if you don't have them, but after that it will copy the patterns folder to the default User directory, `~/.config/ai-buddy/patterns`. And that's where the program will try to find the patterns.
After that you can run: `ai-buddy.exe -w --port 8081` normally.

**Comment by cetorres** [comment]
I could reproduce the error on Windows machine. Will work to fix it. Thanks for finding it!

**Comment by cetorres** [comment]
Ok, fixed the error on patterns listing on Windows. Please take a look on release 1.1.6.

Also found out about the error that appears on Windows only:
```
ERROR unable to locate llm runner directory.  Set OLLAMA_RUNNERS_DIR to the location of 'ollama_runners'
```

To clear that error, just set an environment variable:

```sh
$ set OLLAMA_RUNNERS_DIR=test
```

**Comment by vhongtuanha** [comment]
Thank you. I can confirm it's fixed

**Comment by cetorres** [comment]
Created new release 1.1.7 with more improvements for Windows. Now fixing the color text, that Windows does not support.
